import type { ActivityItem, Instructor, Learner } from "./types"

// All data below is synthetic and clearly fictional.
// Replace these arrays with API calls (e.g. fetch("/api/learners")) later.

export const learners: Learner[] = [
  {
    id: "L-001",
    name: "Ada Whitfield",
    age: 8,
    grade: "3-5",
    learningDifferences: ["Dyslexia", "Reading Difficulty"],
    supportNeeds: ["Reading fluency", "Phonological awareness"],
    availability: ["Mornings", "Weekends"],
    preferredTeachingStyle: "Multisensory",
    notes: "Responds well to hands-on decoding games and short sessions.",
  },
  {
    id: "L-002",
    name: "Mateo Rivera",
    age: 11,
    grade: "6-8",
    learningDifferences: ["ADHD", "Executive Function"],
    supportNeeds: ["Focus & attention", "Organization"],
    availability: ["Afternoons", "Flexible"],
    preferredTeachingStyle: "Goal-oriented",
    notes: "Benefits from clear checklists and frequent movement breaks.",
  },
  {
    id: "L-003",
    name: "Priya Anand",
    age: 9,
    grade: "3-5",
    learningDifferences: ["Dyscalculia", "Math Difficulty"],
    supportNeeds: ["Number sense", "Working memory"],
    availability: ["Mornings"],
    preferredTeachingStyle: "Visual & concrete",
    notes: "Uses manipulatives to build confidence with place value.",
  },
  {
    id: "L-004",
    name: "Jonah Becker",
    age: 14,
    grade: "9-12",
    learningDifferences: ["ASD", "Executive Function"],
    supportNeeds: ["Social communication", "Task initiation"],
    availability: ["Afternoons", "Evenings"],
    preferredTeachingStyle: "Structured & explicit",
    notes: "Prefers predictable routines and advance notice of changes.",
  },
  {
    id: "L-005",
    name: "Sofia Kowalski",
    age: 7,
    grade: "K-2",
    learningDifferences: ["Reading Difficulty"],
    supportNeeds: ["Phonological awareness", "Reading fluency"],
    availability: ["Mornings", "Weekends"],
    preferredTeachingStyle: "Calm & low-pressure",
    notes: "Building early letter-sound confidence with gentle pacing.",
  },
  {
    id: "L-006",
    name: "Eli Thompson",
    age: 12,
    grade: "6-8",
    learningDifferences: ["Writing Difficulty", "Dyslexia"],
    supportNeeds: ["Written expression", "Working memory"],
    availability: ["Evenings", "Flexible"],
    preferredTeachingStyle: "Structured & explicit",
    notes: "Uses graphic organizers to plan multi-paragraph writing.",
  },
  {
    id: "L-007",
    name: "Mia Fernandez",
    age: 10,
    grade: "3-5",
    learningDifferences: ["ADHD"],
    supportNeeds: ["Focus & attention", "Task initiation"],
    availability: ["Afternoons"],
    preferredTeachingStyle: "Flexible & exploratory",
    notes: "Engages best with interest-led projects and choice.",
  },
  {
    id: "L-008",
    name: "Noah Gupta",
    age: 13,
    grade: "6-8",
    learningDifferences: ["Math Difficulty", "Dyscalculia"],
    supportNeeds: ["Number sense", "Organization"],
    availability: ["Mornings", "Afternoons"],
    preferredTeachingStyle: "Visual & concrete",
    notes: "Needs step-by-step models for multi-step problems.",
  },
  {
    id: "L-009",
    name: "Layla Hassan",
    age: 6,
    grade: "K-2",
    learningDifferences: ["ASD", "Reading Difficulty"],
    supportNeeds: ["Sensory regulation", "Phonological awareness"],
    availability: ["Mornings"],
    preferredTeachingStyle: "Calm & low-pressure",
    notes: "Sensory-friendly environment helps sustain attention.",
  },
  {
    id: "L-010",
    name: "Owen Park",
    age: 15,
    grade: "9-12",
    learningDifferences: ["Executive Function", "ADHD"],
    supportNeeds: ["Organization", "Task initiation"],
    availability: ["Evenings", "Weekends"],
    preferredTeachingStyle: "Goal-oriented",
    notes: "Working on long-term planning and assignment tracking.",
  },
  {
    id: "L-011",
    name: "Harper Nguyen",
    age: 9,
    grade: "3-5",
    learningDifferences: ["Dyslexia"],
    supportNeeds: ["Reading fluency", "Written expression"],
    availability: ["Afternoons", "Flexible"],
    preferredTeachingStyle: "Multisensory",
    notes: "Enjoys reading aloud with a supportive partner.",
  },
  {
    id: "L-012",
    name: "Liam O'Connor",
    age: 11,
    grade: "6-8",
    learningDifferences: ["Writing Difficulty"],
    supportNeeds: ["Written expression", "Organization"],
    availability: ["Mornings", "Weekends"],
    preferredTeachingStyle: "Structured & explicit",
    notes: "Dictation tools help bridge ideas to written text.",
  },
  {
    id: "L-013",
    name: "Zoe Castellano",
    age: 8,
    grade: "3-5",
    learningDifferences: ["ADHD", "Math Difficulty"],
    supportNeeds: ["Focus & attention", "Number sense"],
    availability: ["Afternoons"],
    preferredTeachingStyle: "Flexible & exploratory",
    notes: "Short, varied tasks keep engagement high.",
  },
  {
    id: "L-014",
    name: "Aiden Brooks",
    age: 16,
    grade: "9-12",
    learningDifferences: ["Dyslexia", "Executive Function"],
    supportNeeds: ["Reading fluency", "Organization"],
    availability: ["Evenings"],
    preferredTeachingStyle: "Goal-oriented",
    notes: "Preparing for exams with structured study routines.",
  },
  {
    id: "L-015",
    name: "Isla Morgan",
    age: 7,
    grade: "K-2",
    learningDifferences: ["Dyscalculia"],
    supportNeeds: ["Number sense", "Working memory"],
    availability: ["Mornings", "Flexible"],
    preferredTeachingStyle: "Visual & concrete",
    notes: "Counting games and number lines build foundations.",
  },
  {
    id: "L-016",
    name: "Caleb Robinson",
    age: 12,
    grade: "6-8",
    learningDifferences: ["ASD"],
    supportNeeds: ["Social communication", "Sensory regulation"],
    availability: ["Afternoons", "Evenings"],
    preferredTeachingStyle: "Calm & low-pressure",
    notes: "Clear expectations and quiet spaces support success.",
  },
  {
    id: "L-017",
    name: "Nora Lindqvist",
    age: 10,
    grade: "3-5",
    learningDifferences: ["Reading Difficulty", "Writing Difficulty"],
    supportNeeds: ["Reading fluency", "Written expression"],
    availability: ["Mornings", "Weekends"],
    preferredTeachingStyle: "Multisensory",
    notes: "Pairs reading with drawing to deepen comprehension.",
  },
  {
    id: "L-018",
    name: "Diego Santos",
    age: 13,
    grade: "6-8",
    learningDifferences: ["ADHD", "Executive Function"],
    supportNeeds: ["Task initiation", "Focus & attention"],
    availability: ["Afternoons", "Flexible"],
    preferredTeachingStyle: "Goal-oriented",
    notes: "Timers and goal-setting help maintain momentum.",
  },
  {
    id: "L-019",
    name: "Freya Andersson",
    age: 9,
    grade: "3-5",
    learningDifferences: ["Math Difficulty"],
    supportNeeds: ["Number sense", "Focus & attention"],
    availability: ["Mornings"],
    preferredTeachingStyle: "Visual & concrete",
    notes: "Visual models reduce anxiety around math tasks.",
  },
  {
    id: "L-020",
    name: "Theo Marchetti",
    age: 14,
    grade: "9-12",
    learningDifferences: ["Dyslexia", "Writing Difficulty"],
    supportNeeds: ["Written expression", "Reading fluency"],
    availability: ["Evenings", "Weekends"],
    preferredTeachingStyle: "Structured & explicit",
    notes: "Builds essays from outlines with scaffolded support.",
  },
]

export const instructors: Instructor[] = [
  {
    id: "I-001",
    name: "Dr. Rachel Stein",
    title: "Reading Specialist",
    skills: ["Reading fluency", "Phonological awareness", "Written expression"],
    experienceAreas: ["Dyslexia", "Reading Difficulty", "Writing Difficulty"],
    availability: ["Mornings", "Weekends"],
    teachingStyle: "Multisensory",
    capacity: 8,
    currentLoad: 5,
    yearsExperience: 12,
    bio: "Orton-Gillingham trained specialist focused on structured literacy.",
  },
  {
    id: "I-002",
    name: "Marcus Bell",
    title: "Executive Function Coach",
    skills: ["Organization", "Task initiation", "Focus & attention"],
    experienceAreas: ["ADHD", "Executive Function"],
    availability: ["Afternoons", "Evenings", "Flexible"],
    teachingStyle: "Goal-oriented",
    capacity: 10,
    currentLoad: 7,
    yearsExperience: 8,
    bio: "Helps learners build durable planning and self-management habits.",
  },
  {
    id: "I-003",
    name: "Wei Chen",
    title: "Math Intervention Lead",
    skills: ["Number sense", "Working memory", "Organization"],
    experienceAreas: ["Dyscalculia", "Math Difficulty"],
    availability: ["Mornings", "Afternoons"],
    teachingStyle: "Visual & concrete",
    capacity: 9,
    currentLoad: 4,
    yearsExperience: 10,
    bio: "Uses concrete-pictorial-abstract sequencing to grow number sense.",
  },
  {
    id: "I-004",
    name: "Amara Okafor",
    title: "Autism Support Educator",
    skills: ["Social communication", "Sensory regulation", "Task initiation"],
    experienceAreas: ["ASD", "Executive Function"],
    availability: ["Afternoons", "Evenings"],
    teachingStyle: "Calm & low-pressure",
    capacity: 6,
    currentLoad: 3,
    yearsExperience: 9,
    bio: "Creates predictable, sensory-aware learning environments.",
  },
  {
    id: "I-005",
    name: "Hannah Schmidt",
    title: "Early Literacy Tutor",
    skills: ["Phonological awareness", "Reading fluency"],
    experienceAreas: ["Reading Difficulty", "Dyslexia"],
    availability: ["Mornings", "Weekends"],
    teachingStyle: "Calm & low-pressure",
    capacity: 7,
    currentLoad: 6,
    yearsExperience: 6,
    bio: "Specializes in gentle, confidence-building early reading support.",
  },
  {
    id: "I-006",
    name: "David Owusu",
    title: "Writing & Composition Mentor",
    skills: ["Written expression", "Organization", "Working memory"],
    experienceAreas: ["Writing Difficulty", "Dyslexia"],
    availability: ["Evenings", "Flexible"],
    teachingStyle: "Structured & explicit",
    capacity: 8,
    currentLoad: 5,
    yearsExperience: 11,
    bio: "Guides learners from idea to polished writing with scaffolds.",
  },
  {
    id: "I-007",
    name: "Sandra Lopez",
    title: "ADHD Learning Coach",
    skills: ["Focus & attention", "Task initiation", "Organization"],
    experienceAreas: ["ADHD", "Executive Function"],
    availability: ["Afternoons", "Flexible"],
    teachingStyle: "Flexible & exploratory",
    capacity: 9,
    currentLoad: 8,
    yearsExperience: 7,
    bio: "Designs interest-led sessions that sustain attention and motivation.",
  },
  {
    id: "I-008",
    name: "Tomas Novak",
    title: "Numeracy Specialist",
    skills: ["Number sense", "Focus & attention", "Working memory"],
    experienceAreas: ["Math Difficulty", "Dyscalculia", "ADHD"],
    availability: ["Mornings", "Evenings"],
    teachingStyle: "Visual & concrete",
    capacity: 8,
    currentLoad: 2,
    yearsExperience: 9,
    bio: "Reduces math anxiety with visual, low-stakes practice.",
  },
  {
    id: "I-009",
    name: "Grace Kim",
    title: "Multisensory Reading Tutor",
    skills: ["Reading fluency", "Phonological awareness", "Written expression"],
    experienceAreas: ["Dyslexia", "Reading Difficulty"],
    availability: ["Afternoons", "Weekends", "Flexible"],
    teachingStyle: "Multisensory",
    capacity: 7,
    currentLoad: 4,
    yearsExperience: 5,
    bio: "Blends movement, sound, and sight to make reading stick.",
  },
  {
    id: "I-010",
    name: "Benjamin Frost",
    title: "Inclusive Education Generalist",
    skills: ["Organization", "Social communication", "Reading fluency"],
    experienceAreas: ["ASD", "Executive Function", "Reading Difficulty"],
    availability: ["Mornings", "Afternoons", "Flexible"],
    teachingStyle: "Structured & explicit",
    capacity: 10,
    currentLoad: 6,
    yearsExperience: 13,
    bio: "Versatile educator supporting diverse needs across subjects.",
  },
]

export const recentActivity: ActivityItem[] = [
  {
    id: "A-001",
    type: "approval",
    message: "Support plan approved for Ada Whitfield with Dr. Rachel Stein",
    timestamp: "2 hours ago",
  },
  {
    id: "A-002",
    type: "match",
    message: "New match suggested for Mateo Rivera",
    timestamp: "4 hours ago",
  },
  {
    id: "A-003",
    type: "learner",
    message: "Learner profile updated for Priya Anand",
    timestamp: "Yesterday",
  },
  {
    id: "A-004",
    type: "match",
    message: "Match run completed for Jonah Becker",
    timestamp: "Yesterday",
  },
  {
    id: "A-005",
    type: "instructor",
    message: "Tomas Novak added new morning availability",
    timestamp: "2 days ago",
  },
  {
    id: "A-006",
    type: "approval",
    message: "Support plan approved for Owen Park with Marcus Bell",
    timestamp: "3 days ago",
  },
]

export function getLearnerById(id: string | null | undefined): Learner | undefined {
  if (!id) return undefined
  return learners.find((l) => l.id === id)
}

export function getInstructorById(id: string | null | undefined): Instructor | undefined {
  if (!id) return undefined
  return instructors.find((i) => i.id === id)
}
