# Generated by Django 5.2.16 on 2026-07-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructor",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterModelOptions(
            name="learner",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterModelOptions(
            name="learningplan",
            options={"ordering": ["-created_at"]},
        ),
    ]
